#ifndef APPINFO_H
#define APPINFO_H

#define APPNAME "BestroombaN.A."

#define MAJOR_VERSION "0"
#define MINOR_VERSION "0"
#define REVISION_VERSION "1"
#define VERSION MAJOR_VERSION "." MINOR_VERSION "." REVISION_VERSION
#define APPNAME_VERSION APPNAME " v" VERSION

#endif
