#ifndef APPINFO_H
#define APPINFO_H

#define APPNAME "BestRoombaNA"

#define MAJOR_VERSION "0"
#define MINOR_VERSION "4"
#define REVISION_VERSION "24"
#define VERSION MAJOR_VERSION "." MINOR_VERSION "." REVISION_VERSION
#define APPNAME_VERSION APPNAME " v" VERSION

#endif
