#ifndef APPINFO_H
#define APPINFO_H

#define APPNAME "BestRoombaNA"

#define MAJOR_VERSION "2"
#define MINOR_VERSION "1"
#define VERSION MAJOR_VERSION "." MINOR_VERSION
#define APPNAME_VERSION APPNAME " v" VERSION

#endif
